# Anarchy-System Configuration
# Modern homes system with visual layout configuration

modules:
  homes:
    enabled: true

homes:
  default-homes: 1
  max-homes: 10
  luckperms-integration: true
  
  ranks:
    epic:
      homes: 2
      luckperms-group: "epic"
      permission: "anarchy.homes.epic"
    ultra:
      homes: 4
      luckperms-group: "ultra"
      permission: "anarchy.homes.ultra"
    hero:
      homes: 6
      luckperms-group: "hero"
      permission: "anarchy.homes.hero"
    legendary:
      homes: 10
      luckperms-group: "legendary"
      permission: "anarchy.homes.legendary"
  
  gui:
    title: "&6&lHomes Manager"
    
    # Visual GUI Layout - each character = 1 slot
    # . = home slots, # = border, < = previous, > = next, X = close
    layout:
      - "#########"
      - "#.......#"
      - "#.......#"
      - "#.......#"
      - "#.......#"
      - "<###X###>"
    
    # Special items configuration
    items:
      "#":
        material: "GRAY_STAINED_GLASS_PANE"
        name: " "
      "<":
        material: "ARROW"
        name: "&7◀ Previous"
      ">":
        material: "ARROW"
        name: "&7Next ▶"
      "X":
        material: "BARRIER"
        name: "&cClose"
    
    # Home configurations
    homes:
      1:
        material: "WHITE_BED"
        name: "&f&lHome 1"
        rank: "default"
      2:
        material: "LIGHT_GRAY_BED"
        name: "&7&lHome 2 &8[Epic]"
        rank: "epic"
      3:
        material: "ORANGE_BED"
        name: "&6&lHome 3 &8[Ultra]"
        rank: "ultra"
      4:
        material: "ORANGE_BED"
        name: "&6&lHome 4 &8[Ultra]"
        rank: "ultra"
      5:
        material: "BLUE_BED"
        name: "&9&lHome 5 &8[Hero]"
        rank: "hero"
      6:
        material: "BLUE_BED"
        name: "&9&lHome 6 &8[Hero]"
        rank: "hero"
      7:
        material: "PURPLE_BED"
        name: "&5&lHome 7 &8[Legendary]"
        rank: "legendary"
      8:
        material: "PURPLE_BED"
        name: "&5&lHome 8 &8[Legendary]"
        rank: "legendary"
      9:
        material: "PURPLE_BED"
        name: "&5&lHome 9 &8[Legendary]"
        rank: "legendary"
      10:
        material: "PURPLE_BED"
        name: "&5&lHome 10 &8[Legendary]"
        rank: "legendary"

messages:
  commands:
    home-set: "&a&l✓ &7Home &6%home% &7set successfully!"
    home-teleported: "&a&l➤ &7Teleported to home &6%home%"
    home-deleted: "&c&l✗ &7Home &6%home% &7deleted!"
    home-not-found: "&c&l! &7Home &6%home% &7not found"
    max-homes-reached: "&c&l! &7Maximum homes reached"
    no-permission: "&c&l! &7No permission"
    invalid-number: "&c&l! &7Invalid home number"
    config-reloaded: "&a&l✓ &7Configuration reloaded"
  
  gui:
    home-set-lore:
      - "&7World: &f%world%"
      - "&7Location: &f%x%, %y%, %z%"
      - ""
      - "&a▶ Left-click to teleport"
      - "&c▶ Right-click to delete"
    
    home-empty-lore:
      - "&7This home is not set"
      - ""
      - "&e▶ Use &6/sethome %number%"
    
    home-locked-lore:
      - "&c&l🔒 LOCKED"
      - "&7Required rank: &6%rank%"
      - ""
      - "&7Upgrade to &6%rank% &7rank"
      - "&7to unlock this home"
    
    messages:
      no-access: "&c&l! &7You cannot access this home"
      world-not-found: "&c&l! &7Home world not found"
  
  ranks:
    default: "&f&lDefault"
    epic: "&6&lEpic"
    ultra: "&6&lUltra"
    hero: "&9&lHero"
    legendary: "&5&lLegendary"