# ==========================================
#           ANARCHY SYSTEM CONFIG
# ==========================================
# Modern homes system with GUI management
# UTF-8 Support enabled

# Module Configuration
modules:
  homes:
    enabled: true

# Homes System Configuration
homes:
  # Basic Settings
  default-homes: 1
  max-homes: 10
  luckperms-integration: true
  
  # Rank System
  ranks:
    epic:
      homes: 2
      luckperms-group: "epic"
      permission: "anarchy.homes.epic"
    ultra:
      homes: 4
      luckperms-group: "ultra"
      permission: "anarchy.homes.ultra"
    hero:
      homes: 6
      luckperms-group: "hero"
      permission: "anarchy.homes.hero"
    legendary:
      homes: 10
      luckperms-group: "legendary"
      permission: "anarchy.homes.legendary"
  
  # GUI Configuration
  gui:
    title: "&8[&6Homes&8] &7Manager"
    
    # Layout Design (9x6 inventory)
    # Symbols: . = home slot, # = border, < = previous, > = next, X = close
    layout:
      - "#########"
      - "#.......#"
      - "#.......#"
      - "#.......#"
      - "#.......#"
      - "<###X###>"
    
    # Interface Elements
    items:
      "#":
        material: "BLACK_STAINED_GLASS_PANE"
        name: " "
      "<":
        material: "ARROW"
        name: "&7Previous Page"
      ">":
        material: "ARROW"
        name: "&7Next Page"
      "X":
        material: "BARRIER"
        name: "&cClose Menu"
    
    # Home Item Configurations
    homes:
      1:
        material: "WHITE_BED"
        name: "&fHome 1"
        rank: "default"
      2:
        material: "ORANGE_BED"
        name: "&6Home 2 &8- Epic"
        rank: "epic"
      3:
        material: "ORANGE_BED"
        name: "&6Home 3 &8- Ultra"
        rank: "ultra"
      4:
        material: "ORANGE_BED"
        name: "&6Home 4 &8- Ultra"
        rank: "ultra"
      5:
        material: "LIGHT_BLUE_BED"
        name: "&bHome 5 &8- Hero"
        rank: "hero"
      6:
        material: "LIGHT_BLUE_BED"
        name: "&bHome 6 &8- Hero"
        rank: "hero"
      7:
        material: "PURPLE_BED"
        name: "&dHome 7 &8- Legendary"
        rank: "legendary"
      8:
        material: "PURPLE_BED"
        name: "&dHome 8 &8- Legendary"
        rank: "legendary"
      9:
        material: "PURPLE_BED"
        name: "&dHome 9 &8- Legendary"
        rank: "legendary"
      10:
        material: "PURPLE_BED"
        name: "&dHome 10 &8- Legendary"
        rank: "legendary"

# Message Configuration
messages:
  # Command Messages
  commands:
    home-set: "&a&lSUCCESS &8» &7Home &f%home% &7has been set"
    home-teleported: "&a&lTELEPORT &8» &7Teleported to home &f%home%"
    home-deleted: "&c&lDELETED &8» &7Home &f%home% &7has been removed"
    home-not-found: "&c&lERROR &8» &7Home &f%home% &7does not exist"
    max-homes-reached: "&c&lLIMIT &8» &7You have reached your home limit"
    no-permission: "&c&lERROR &8» &7Insufficient permissions"
    invalid-number: "&c&lERROR &8» &7Invalid home number provided"
    config-reloaded: "&a&lRELOAD &8» &7Configuration has been reloaded"
  
  # GUI Messages
  gui:
    # Home Item Descriptions
    home-set-lore:
      - "&7World: &f%world%"
      - "&7Position: &f%x% &8/ &f%y% &8/ &f%z%"
      - ""
      - "&aLeft Click &8» &7Teleport"
      - "&cRight Click &8» &7Delete Home"
    
    home-empty-lore:
      - "&7This home slot is empty"
      - ""
      - "&eUse command: &6/sethome %number%"
    
    home-locked-lore:
      - "&c&lLOCKED SLOT"
      - "&7Required Rank: &f%rank%"
      - ""
      - "&7Upgrade your rank to unlock"
      - "&7this home slot"
    
    # GUI Interaction Messages
    messages:
      no-access: "&c&lERROR &8» &7You cannot access this home slot"
      world-not-found: "&c&lERROR &8» &7Home world no longer exists"
  
  # Rank Display Names
  ranks:
    default: "&7Default"
    epic: "&6Epic"
    ultra: "&6Ultra"
    hero: "&bHero"
    legendary: "&dLegendary"