# ==========================================
#           ANARCHY SYSTEM CONFIG
# ==========================================
# Modern homes system with GUI management
# UTF-8 Support enabled

# Module Configuration
modules:
  homes:
    enabled: true
  home-particles:
    enabled: true
  teleport:
    enabled: true
  teleport-animation:
    enabled: true

# Teleport System Configuration
teleport:
  tpa-timeout: 60
  tpa-cooldown: 30
  back-cooldown: 10

# Teleport Animation Configuration
teleport-animation:
  enabled: true
  duration: 6
  radius: 1.0
  view-distance: 40.0
  movement-threshold: 0.5

  # Spiral Animation (upward spiraling particles)
  spiral:
    enabled: true
    height: 2.0
    y-offset: 0.2
    particle-count: 6
    turns: 3.0
    particle-type: "DUST_COLOR_TRANSITION"
    particle-color: "255,215,0-255,69,0"

  # Circle Animation (rotating circle particles)
  circle:
    enabled: true
    particle-count: 3
    rotation-speed: 0.19634954084936207
    y-offset: 0.1
    particle-type: "ELECTRIC_SPARK"
    particle-color: "0,255,255"

  # Destination Animation (show particles at teleport destination)
  destination:
    enabled: true

  # Sound Configuration
  sounds:
    loop: "ENTITY_BAT_TAKEOFF"
    final: "ITEM_CHORUS_FRUIT_TELEPORT"
    volume: 0.5
    pitch: 1.0

# Home Location Particles Configuration
home-particles:
  detection-radius: 40.0
  circle-radius: 0.75
  particle-count: 3
  y-offset: 0.2
  rotation-speed: 0.05
  particle-type: "DUST_COLOR_TRANSITION"
  color: "255,0,0-0,0,255"

# Homes System Configuration
homes:
  default-homes: 1
  max-homes: 10
  luckperms-integration: true
  
  ranks:
    epic:
      homes: 2
      luckperms-group: "epic"
      permission: "anarchy.homes.epic"
    ultra:
      homes: 4
      luckperms-group: "ultra"
      permission: "anarchy.homes.ultra"
    hero:
      homes: 6
      luckperms-group: "hero"
      permission: "anarchy.homes.hero"
    legendary:
      homes: 10
      luckperms-group: "legendary"
      permission: "anarchy.homes.legendary"
  
  gui:
    title: "&8[&6Homes&8] &7Manager"
    
    layout:
      - "#########"
      - "#0000000#"
      - "#0.....0#"
      - "#0.....0#"
      - "#0000000#"
      - "<###X###>"
    
    items:
      "#":
        material: "BLACK_STAINED_GLASS_PANE"
        name: " "
      "<":
        material: "ARROW"
        name: "&7Previous Page"
      ">":
        material: "ARROW"
        name: "&7Next Page"
      "X":
        material: "BARRIER"
        name: "&cClose Menu"
    
    homes:
      1:
        material: "WHITE_BED"
        name: "&fHome 1"
        rank: "default"
      2:
        material: "ORANGE_BED"
        name: "&6Home 2 &8- Epic"
        rank: "epic"
      3:
        material: "ORANGE_BED"
        name: "&6Home 3 &8- Ultra"
        rank: "ultra"
      4:
        material: "ORANGE_BED"
        name: "&6Home 4 &8- Ultra"
        rank: "ultra"
      5:
        material: "LIGHT_BLUE_BED"
        name: "&bHome 5 &8- Hero"
        rank: "hero"
      6:
        material: "LIGHT_BLUE_BED"
        name: "&bHome 6 &8- Hero"
        rank: "hero"
      7:
        material: "PURPLE_BED"
        name: "&dHome 7 &8- Legendary"
        rank: "legendary"
      8:
        material: "PURPLE_BED"
        name: "&dHome 8 &8- Legendary"
        rank: "legendary"
      9:
        material: "PURPLE_BED"
        name: "&dHome 9 &8- Legendary"
        rank: "legendary"
      10:
        material: "PURPLE_BED"
        name: "&dHome 10 &8- Legendary"
        rank: "legendary"

# ==========================================
#           PARTICLE TYPE REFERENCE
# ==========================================
# 
# COLORABLE PARTICLES (support color configuration):
# ┌─────────────────────────────────────────────────────────────────┐
# │ DUST                    - RGB format: "255,0,0"                │
# │ DUST_COLOR_TRANSITION   - RGB1-RGB2 format: "255,0,0-0,0,255"  │
# │ ENTITY_EFFECT          - RGB format: "255,0,0"                 │
# │ REDSTONE               - RGB format: "255,0,0" (legacy)        │
# └─────────────────────────────────────────────────────────────────┘
#
# NON-COLORABLE PARTICLES (ignore color setting):
# ┌─────────────────────────────────────────────────────────────────┐
# │ ELECTRIC_SPARK    FIREWORK           FLAME             HEART    │
# │ ENCHANT          CRIT               MAGIC_CRIT         SPELL     │
# │ INSTANT_SPELL    MOB_SPELL          WITCH_SPELL        NOTE      │
# │ PORTAL           ENCHANTMENT_TABLE  EXPLOSION          EXPLOSION_LARGE │
# │ EXPLOSION_HUGE   WATER_BUBBLE       WATER_SPLASH       WATER_WAKE │
# │ SUSPENDED        SUSPENDED_DEPTH    CRIT_MAGIC         SMOKE_NORMAL │
# │ SMOKE_LARGE      SPELL_MOB          SPELL_MOB_AMBIENT  SPELL_WITCH │
# │ DRIP_WATER       DRIP_LAVA          ANGRY_VILLAGER     HAPPY_VILLAGER │
# │ TOWN_AURA        NOTE_BLOCK         PORTAL_AMBIENT     SNOWBALL │
# │ SNOW_SHOVEL      SLIME              END_ROD            DRAGON_BREATH │
# │ DAMAGE_INDICATOR SWEEP_ATTACK       FALLING_DUST       │
# └─────────────────────────────────────────────────────────────────┘

messages:
  commands:
    home-set: "&a&lSUCCESS &8» &7Home &f%home% &7has been set"
    home-teleported: "&a&lTELEPORT &8» &7Teleported to home &f%home%"
    home-deleted: "&c&lDELETED &8» &7Home &f%home% &7has been removed"
    home-not-found: "&c&lERROR &8» &7Home &f%home% &7does not exist"
    max-homes-reached: "&c&lLIMIT &8» &7You have reached your home limit"
    no-permission: "&c&lERROR &8» &7Insufficient permissions"
    invalid-number: "&c&lERROR &8» &7Invalid home number provided"
    config-reloaded: "&a&lRELOAD &8» &7Configuration has been reloaded"
  
  teleport:
    tpa-sent: "&a&lTPA &8» &7Teleport request sent to &f%player%"
    tpa-received: "&6&lTPA &8» &f%player% &7wants to teleport to you"
    tpahere-sent: "&a&lTPAHERE &8» &7Teleport request sent to &f%player%"
    tpahere-received: "&6&lTPAHERE &8» &f%player% &7wants you to teleport to them"
    tpa-accepted: "&a&lACCEPTED &8» &f%player% &7accepted your teleport request"
    tpa-accepted-target: "&a&lACCEPTED &8» &7You accepted &f%player%&7's teleport request"
    tpa-denied: "&c&lDENIED &8» &f%player% &7denied your teleport request"
    tpa-denied-target: "&c&lDENIED &8» &7You denied &f%player%&7's teleport request"
    tpa-timeout: "&c&lTIMEOUT &8» &7Teleport request to &f%player% &7has expired"
    tpa-timeout-target: "&c&lTIMEOUT &8» &7Teleport request from &f%player% &7has expired"
    teleport-cancelled-movement: "&c&lCANCELLED &8» &7Teleport cancelled due to movement"
    
    tpa-self: "&c&lERROR &8» &7You cannot send a teleport request to yourself"
    tpa-disabled: "&c&lERROR &8» &f%player% &7has teleport requests disabled"
    tpa-blocked: "&c&lERROR &8» &f%player% &7has blocked your teleport requests"
    tpa-pending: "&c&lERROR &8» &f%player% &7already has a pending teleport request"
    tpa-cooldown: "&c&lCOOLDOWN &8» &7Wait &f%time% &7seconds before sending another request"
    player-not-found: "&c&lERROR &8» &7Player &f%player% &7is not online"
    no-pending-request: "&c&lERROR &8» &7You have no pending teleport requests"
    requester-offline: "&c&lERROR &8» &7The player who sent the request is no longer online"
    
    tpa-enabled-self: "&a&lTPA &8» &7Teleport requests are now &aenabled"
    tpa-disabled-self: "&c&lTPA &8» &7Teleport requests are now &cdisabled"
    
    back-teleported: "&a&lBACK &8» &7Teleported to your previous location"
    back-cooldown: "&c&lCOOLDOWN &8» &7Wait &f%time% &7seconds before using /back again"
    no-back-location: "&c&lERROR &8» &7No previous location found"
    back-world-not-found: "&c&lERROR &8» &7Your previous location's world no longer exists"
    
    tpa-usage: "&c&lUSAGE &8» &7/tpa <player>"
    tpahere-usage: "&c&lUSAGE &8» &7/tpahere <player>"
  
  gui:
    home-set-lore:
      - "&7World: &f%world%"
      - "&7Position: &f%x% &8/ &f%y% &8/ &f%z%"
      - ""
      - "&aLeft Click &8» &7Teleport"
      - "&cRight Click &8» &7Delete Home"
    
    home-empty-lore:
      - "&7This home slot is empty"
      - ""
      - "&eUse command: &6/sethome %number%"
    
    home-locked-lore:
      - "&c&lLOCKED SLOT"
      - "&7Required Rank: &f%rank%"
      - ""
      - "&7Upgrade your rank to unlock"
      - "&7this home slot"
    
    messages:
      no-access: "&c&lERROR &8» &7You cannot access this home slot"
      world-not-found: "&c&lERROR &8» &7Home world no longer exists"
  
  ranks:
    default: "&7Default"
    epic: "&6Epic"
    ultra: "&6Ultra"
    hero: "&bHero"
    legendary: "&dLegendary"